apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "redis-enterprise.fullname" . }}
  labels:
    app: {{ template "redis-enterprise.name" . }}
    chart: {{ template "redis-enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "patch"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "update", "patch", "create", "delete"]
