apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "redis-enterprise.fullname" . }}
  labels:
    app: {{ template "redis-enterprise.name" . }}
    chart: {{ template "redis-enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "redis-enterprise.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "redis-enterprise.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
