apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "redis-enterprise.serviceAccountName" . }}
  labels:
    app: {{ template "redis-enterprise.name" . }}
    chart: {{ template "redis-enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
